### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by canselcik** [StanfordSNR/gg#17]
Hi,

Build fails with the following:

```
make[3]: Entering directory '/home/main/Desktop/gg/src/sandbox'
  CXX      sandbox.o
  AR       libggsandbox.a
make[3]: Leaving directory '/home/main/Desktop/gg/src/sandbox'
Making all in models
make[3]: Entering directory '/home/main/Desktop/gg/src/models'
./generate-toolchain-header.py /home/main/Desktop/gg/toolchain/bin
./generate-toolchain-header.py /home/main/Desktop/gg/toolchain/bin
Traceback (most recent call last):
  File "./generate-toolchain-header.py", line 86, in <module>
    c_include_path = get_include_path()
  File "./generate-toolchain-header.py", line 32, in get_include_path
    output = sub.check_output(command, stderr=sub.STDOUT, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 219, in check_output
Traceback (most recent call last):
  File "./generate-toolchain-header.py", line 86, in <module>
    c_include_path = get_include_path()
  File "./generate-toolchain-header.py", line 32, in get_include_path
    output = sub.check_output(command, stderr=sub.STDOUT, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessErrorsubprocess.CalledProcessError: : Command 'gcc-7 -E -Wp,-v - < /dev/null >/dev/null' returned non-zero exit status 127Command 'gcc-7 -E -Wp,-v - < /dev/null >/dev/null' returned non-zero exit status 127

make[3]: *** [Makefile:707: toolchain.hh] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [Makefile:707: toolchain.cc] Error 1
make[3]: Leaving directory '/home/main/Desktop/gg/src/models'
make[2]: *** [Makefile:343: all-recursive] Error 1
make[2]: Leaving directory '/home/main/Desktop/gg/src'
make[1]: *** [Makefile:386: all-recursive] Error 1
make[1]: Leaving directory '/home/main/Desktop/gg'
make: *** [Makefile:327: all] Error 2
```

Let me know if you need more information.

Thanks.

**Comment by sadjad** [comment]
Hi,

Currently, you need gcc 7 to build `gg`. It seems that you don't have gcc-7 installed on your system.

Cheers,
Sadjad
